vector_version: 0.22.0
vector_dirs: "vector"
arch: x86_64
vector_config_dir: "/etc/vector"

vector_config:

  sources:
    demo_logs:
      type: demo_logs
      format: syslog
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - demo_logs
      database: logs
      endpoint: http://{{ clickhouse_01_ext_ip }}:8123
      table: logs.alerts
      compression: gzip
      healthcheck: true
      skip_unknown_fields: true